# Generated by Django 5.2.6 on 2025-09-10 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_tokens'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tokens',
            name='date',
        ),
        migrations.AddField(
            model_name='tokens',
            name='created_at',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='created_at'),
        ),
    ]
