# Generated by Django 5.2.6 on 2025-09-13 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_tokens_date_tokens_created_at'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tokens',
        ),
    ]
